### ISSUE TITLE
sftp path is not configurable

### ISSUE THREAD

**Issue by lizrea** [bywatersolutions/koha-plugin-message-bee#1]
Unique sometimes gives out different upload directories to their clients, currently the directory is hard coded to "cust2unique" - it would be neat to be able to configure this from the plugin interface.

Liz

**Comment by kylemhall** [comment]
MessageBee plugin now has an environment variable `MESSAGEBEE_SFTP_DIR` that can override the default `cust2unique` SFTP path directory!
